import { Product } from '@/store/useCartStore';

export const products: Product[] = [
  {
    id: '1',
    name: 'Executive Managerial Desk',
    price: 48500,
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80',
    category: 'Office Furniture',
    rating: 4.9,
    reviews: 24,
    description: 'Premium dark-wood executive table featuring built-in side drawers, cable management channels, and a scratch-resistant melamine finish.',
    material: 'Laminated Wood & Stainless Steel',
    dimensions: '66" W x 32" D x 30" H',
    stock: 12,
  },
  {
    id: '2',
    name: 'Ergonomic Executive High-Back Chair',
    price: 26500,
    image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d12bd?w=600&q=80',
    category: 'Executive Chairs',
    rating: 4.8,
    reviews: 38,
    description: 'Heavy-duty ergonomic office chair with headrest support, lumbar cushion, pneumatic height adjustment, and smooth 360-degree swivel wheels.',
    material: 'Breathable Mesh & Aluminum Base',
    dimensions: '26" W x 26" D x 48-52" H',
    stock: 25,
  },
  {
    id: '3',
    name: 'Orthopedic Multi-Layer Foam Mattress',
    price: 34000,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    category: 'Foam & Mattresses',
    rating: 5.0,
    reviews: 42,
    description: 'High-density pressure-relieving orthopedic foam mattress engineered for optimal spinal support, restful sleep, and long-lasting resilience.',
    material: 'High-Density Memory Foam & Quilted Cotton',
    dimensions: '78" L x 72" W x 8" H (King Size)',
    stock: 15,
  },
  {
    id: '4',
    name: 'Heavy-Duty Plastic Armchairs (Set of 4)',
    price: 14500,
    image: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=600&q=80',
    category: 'Plastic Items',
    rating: 4.7,
    reviews: 19,
    description: 'Stackable, weather-proof plastic chairs crafted from 100% virgin polymer plastic. Ideal for gardens, outdoor events, and waiting areas.',
    material: 'Virgin Molded Plastic Polymer',
    dimensions: '22" W x 22" D x 32" H',
    stock: 30,
  },
  {
    id: '5',
    name: 'Luxury Leatherette Executive Sofa Set (3+1+1)',
    price: 89000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
    category: 'Sofa Sets',
    rating: 4.9,
    reviews: 16,
    description: 'Ultra-luxurious 5-seater executive sofa set with plush high-resilience foam padding and stain-resistant premium leatherette finish.',
    material: 'Hardwood Frame, Premium Foam & Leatherette',
    dimensions: '3-Seater: 82" W x 34" D x 34" H',
    stock: 6,
  },
  {
    id: '6',
    name: 'Heavy Steel Filing & Storage Cabinet',
    price: 29500,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&q=80',
    category: 'Storage Solutions',
    rating: 4.8,
    reviews: 11,
    description: 'Four-door heavy-gauge steel document filing cabinet equipped with master lock mechanism, adjustable shelves, and powder-coated finish.',
    material: 'Cold-Rolled Gauge Steel',
    dimensions: '36" W x 18" D x 72" H',
    stock: 10,
  },
  {
    id: '7',
    name: '4-Person Modular Office Workstation',
    price: 76000,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80',
    category: 'Office Furniture',
    rating: 4.9,
    reviews: 14,
    description: 'Complete 4-person workstation layout featuring privacy partition screens, integrated power outlets, and spacious desk surfaces.',
    material: 'Engineered Wood & Steel Legs',
    dimensions: '96" W x 48" D x 42" H',
    stock: 5,
  },
  {
    id: '8',
    name: 'Modern Conference & Meeting Table',
    price: 58000,
    image: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=600&q=80',
    category: 'Office Furniture',
    rating: 4.8,
    reviews: 9,
    description: 'Spacious 8-seater conference table with central cable popup box and rich walnut veneer finish.',
    material: 'Walnut Wood Veneer & Metal Base',
    dimensions: '96" L x 42" W x 30" H',
    stock: 4,
  },
];

export const categories = [
  { name: 'Office Furniture', icon: 'Briefcase', description: 'Executive Desks, Workstations & Meeting Tables' },
  { name: 'Executive Chairs', icon: 'Armchair', description: 'Ergonomic High-Back & Mesh Office Chairs' },
  { name: 'Foam & Mattresses', icon: 'Bed', description: 'Orthopedic & High-Density Comfort Mattresses' },
  { name: 'Plastic Items', icon: 'Sparkles', description: 'Heavy-Duty & Stackable Plastic Furniture' },
  { name: 'Sofa Sets', icon: 'Sofa', description: 'Luxury Leatherette & Fabric Executive Sofas' },
  { name: 'Storage Solutions', icon: 'Box', description: 'Steel Cabinets, File Racks & Lockers' },
];

export const storeInfo = {
  name: 'Abdullah Foam, Plastic & Office Furniture',
  shortName: 'Abdullah Furniture',
  address: 'Kharkhana Bazar, Near Meezan Bank, Vehari',
  city: 'Vehari',
  phone: '0300-0036047',
  rawPhone: '03000036047',
  whatsapp: '923000036047',
  tagline: 'Transform Your Office Into A Premium Workspace',
  highlights: [
    'Premium Quality',
    'Modern Designs',
    'Best Prices',
    'Strong & Durable',
    'Complete Office Solutions Under One Roof'
  ]
};
