import { Product } from '@/store/useCartStore';

export const products: Product[] = [
  {
    id: '1',
    name: 'Modern Lounge Chair',
    price: 28500,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500&q=80',
    category: 'Chairs',
    rating: 4.8,
    reviews: 12,
    description: 'A comfortable and stylish modern lounge chair perfect for any living room.',
    material: 'Wood, Fabric',
    dimensions: '30" W x 32" D x 34" H',
    stock: 15,
  },
  {
    id: '2',
    name: 'Solid Wood Dining Table',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=500&q=80',
    category: 'Tables',
    rating: 4.9,
    reviews: 8,
    description: 'A sturdy solid wood dining table that seats six comfortably.',
    material: 'Solid Oak',
    dimensions: '72" L x 36" W x 30" H',
    stock: 10,
  },
  {
    id: '3',
    name: 'Executive Office Desk',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&q=80',
    category: 'Desks',
    rating: 4.7,
    reviews: 15,
    description: 'Sleek executive office desk with ample storage and workspace.',
    material: 'Wood, Metal',
    dimensions: '60" L x 24" W x 30" H',
    stock: 8,
  },
  {
    id: '4',
    name: 'Comfort 3-Seater Sofa',
    price: 75000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80',
    category: 'Sofas',
    rating: 4.9,
    reviews: 20,
    description: 'Ultra-comfortable 3-seater sofa with plush cushions.',
    material: 'Velvet, Foam',
    dimensions: '84" L x 36" D x 32" H',
    stock: 5,
  },
];

export const categories = [
  { name: 'Chairs', icon: 'Armchair' },
  { name: 'Tables', icon: 'Table' },
  { name: 'Desks', icon: 'Monitor' },
  { name: 'Sofas', icon: 'Sofa' },
  { name: 'Beds', icon: 'Bed' },
  { name: 'Wardrobes', icon: 'Box' },
];
